### PR TITLE
Add myself (belak) as the current maintainer

### PR DESCRIPTION
**Pull request by belak**
I am interested in maintaining this. Are there any expectations outside what was listed in the readme?

The PRs I opened previously are:
#119, #120, #121, #122, and #123

I've also commented on a number of the issues (and potentially fixed one of them) so I'm familiar with most of them as well.

### CODE REVIEW

**Comment by jodal** [comment]
Thanks for taking this on! We've needed a maintainer for Mopidy-GMusic for a very long time :-)

I think the README mentions the most important things. In addition it would be nice if you had time to keep an eye on https://discuss.mopidy.com and #mopidy on IRC for GMusic related issues, but anything is better than nothing at this point.

Do you have a user account at [PyPI](https://pypi.python.org/pypi) which I can give access to make releases?

**Comment by jodal** [comment]
Another note: It might make sense to call your first release 2.0, just to have a clear cut between the old and the new.

**Comment by belak** [comment]
Yep, I'm already in IRC. I just made a PyPI account today (belak) and I'll try to keep my eye on that site.

I've still got some ideas for caching improvements, in particular for the playlists portion, which I'd like to get in before an actual release, but I'll make sure to do that.

**Comment by jodal** [comment]
You should have access to Mopidy-GMusic on PyPI now.

A spring cleaning of open issues and pull requests would be nice. Remember to keep the changelog up to date! :-)

**Comment by belak** [comment]
Yep, looks like that's working. I'm already updating the changelog, but it looks like I don't have access to push to this repo yet.

**Comment by jodal** [comment]
You should have an invite from GitHub in your inbox?

**Comment by jodal** [comment]
If you can't find it, you should be able to accept it anyway by going to https://github.com/mopidy

**Comment by belak** [comment]
Got it, thanks!

**Pull request merged**
