### PR TITLE
Implemented get_distinct in library provider

### PR DESCRIPTION
**Pull request by 6ixisgood**
Implemented enough so that the Media Library tab in ncmpcpp will get the list of artists needed to display content

### CODE REVIEW

**Comment by kingosticks** [comment]
This is great. As it happens I've been doing some work to improve get_distinct at https://github.com/mopidy/mopidy/pull/1900 and it'd be great if you could support track_name as well as  well as track (and any of the other new fields if you wish).

**Comment by kingosticks** [comment]
Cheers for making that change. But am I missing something, where are you using the `query` here? Is there more coming? Doesn't this just dump all the values for the given field?

**Comment by sixisgoood** [comment]
Yes, sorry.  I was reading through how some of the other extensions use the query feature.  Not sure if I should implement it to query off just the user's library or not.

**Comment by kingosticks** [comment]
It's tricky to do something sensible with online catalogues. I think what mopidy-spotify does is reasonable but could be improved to use the entire users library rather than just their playlists in the case where a query was not specified.

**Comment by sixisgoood** [comment]
This now just uses the same method gmusic does for search.  So it will either get the user's library or get their library and search the catalog, depending on if a query is specified.

**Comment by jodal** [comment]
Closing because Google Play Music has been shut down, and this project is being discontinued.

**Pull request closed without merging**
