### PR TITLE
Enable download buffering to improve playback performance

### LINKED ISSUE #160: Playing stops after prolonged pause
Tested on ncmpc through the mpd interface.

To replicate: pause a song for a decent period of time (>2 minutes?), unpausing will allow the song to play again for around 30 seconds and then the playing will stop, appearing to go to the beginning of the track in the unpaused state and frozen.

It's possible this is simply a buffering issue, however this never seems to happen with continuous playback.

### LINKED ISSUE #161: Randomly stops playing after few minutes
Can’t get gmusic plugin to work normally. It starts playing, but after a some time (few minutes) randomly stops. There appears message on console:
`ERROR    GStreamer error: gst-resource-error-quark: Forbidden (15)`

Switching to next track fixes problem for the next few minutes.
Tried on my Raspberry PI 1, Raspberry PI 2, Odroid C2, and on PC. Distros: Ubuntu, Debian, Raspbian, Volumio, Ubuntu on C2. Tried on 3 diffirent USB dacs, and on I2S  dac. Also, mopidy was installed from deb-repo, or from pip. In all cases problem appears.
Now using last versions of mopidy and mopidy from pip: mopidy=2.0.1, mopidy-gmusic=2.0.0. Also, gstreamer1.0.

### PR DESCRIPTION
**Pull request by jjok**
Fixes #161 
Fixes #160

Relies on mopidy/mopidy#1888

### CODE REVIEW

**Comment by belak** [comment]
Does this mean we should bump the required modify version? Thanks for pushing this across the finish line btw!

**Comment by jjok** [comment]
Oh, I hadn't thought of that. It's not actually a requirement. It's just that this new method won't mean anything with an older version.
I guess it's required of you want this extension to work well, but we'd have to wait for a Mopidy release before merging this.
What do you think?

**Comment by kingosticks** [comment]
FYI I'm just adding the uri parameter to `should_download`, might as well get that in there now.

**Comment by jjok** [comment]
Ok. Is that just so it has the same interface as `is_live()` or can you see a situation where the method might need to do some logic based on the uri?

**Comment by kingosticks** [comment]
Mostly the second. There might be a day when we tell this workaround isn't required for certain tracks, or where we want to avoid doing it for really long tracks. I see no reason not to pass this extra information in and make the API more flexible, the backend does not have to use it.

**Comment by jjok** [comment]
I'll add that Param here too then, yeah?

**Comment by kingosticks** [comment]
> I'll add that param here too then, yeah?

Sorry, yes. We've merged https://github.com/mopidy/mopidy/pull/1907 and added the new API to the v3.1 milestone, so that's the new minimum Mopidy version you must target if using `should_download`. There's only currently one other thing to finish off in v3.1 before releasing so hopefully it won't be long.

**Comment by jodal** [comment]
Closing because Google Play Music has been shut down, and this project is being discontinued.

**Pull request closed without merging**
